{
 "title": "NasaLog",
 "time": { "from": "1995-07-04T06:56:48.000Z", "to": "1995-08-29T08:05:34.000Z" },
 "panels": [
  {
   "title": "Bytes request",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "target": "select * from log limit 20;" }
   ]
  },
  {
   "title": "Extensions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select extension, bytes\nfrom loganalysis.log\nlimit 1000;"
    }
   ]
  },
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "select * from loganalysis.log limit 100;"
    }
   ]
  },
  {
   "title": "Request",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select time, bytes, host\nfrom loganalysis.log \nlimit 10;"
    }
   ]
  }
 ]
}